public class BAFCORoutingDetailsDto {
    public BAFCORoutingDetailsDto(){
        containerRecord = new List<BAFCORoutingDetailsDto.containerRecord>();
    }
    @AuraEnabled
    public String routeId { get; set; }
    @AuraEnabled
    public String routeName { get; set; }
    @AuraEnabled
    public String routingRegular { get; set; }
    @AuraEnabled
    public String shipmentKind { get; set; }
    @AuraEnabled
    public String serviceType { get; set; }
    @AuraEnabled
    public String incoTerm { get; set; }
    @AuraEnabled
    public String incoTermName { get; set; }
    @AuraEnabled
    public String incoTermId { get; set; }
    @AuraEnabled
    public String portLoading { get; set; }
     @AuraEnabled
    public String portLoadingId { get; set; }
    @AuraEnabled
    public String placeOfPickup { get; set; }
    @AuraEnabled
    public String placeOfDischarge { get; set; }
    @AuraEnabled
    public String placeOfPickupName { get; set; }
    @AuraEnabled
    public String placeOfDischargeName { get; set; }
    @AuraEnabled
    public String dgClass { get; set; }
    @AuraEnabled
    public String portDestination { get; set; }
    @AuraEnabled
    public String portDestinationId { get; set; }
    @AuraEnabled
    public String shippingLine { get; set; }
    @AuraEnabled
    public String shippingLineName { get; set; }
    @AuraEnabled
    public String commodity { get; set; }
    @AuraEnabled
    public String commodityName { get; set; }
    @AuraEnabled
    public Decimal cargoWeights { get; set; }
    @AuraEnabled
    public Boolean dangerousGoods { get; set; }
    @AuraEnabled
    public String remarks { get; set; }
    @AuraEnabled
    public String leadIndex { get; set; }
    @AuraEnabled
    public String leadId { get; set; }
    @AuraEnabled
    public String businessType { get; set; }
    @AuraEnabled
    public String enquiryId { get; set; }
    @AuraEnabled
    public Decimal accountAvgMargin { get; set; }
    @AuraEnabled
    public Decimal accountBestMargin { get; set; }
    @AuraEnabled
    public Decimal accountAvgCreditDays { get; set; }
    @AuraEnabled
    public String parentId { get; set; }
    @AuraEnabled
    public String cargoReadiness { get; set; }
    @AuraEnabled
    public String equipmentType { get; set; }
    @AuraEnabled
    public String cargoDetails { get; set; }
    @AuraEnabled public String acctName { get; set; }
    @AuraEnabled
    public List<BAFCORoutingDetailsDto.containerRecord> containerRecord { get; set; }
    @AuraEnabled
    public Boolean isAir { get; set; }
    
    public class containerRecord{
        @AuraEnabled
        public String containerType { get; set; }
        @AuraEnabled
        public String containerTypeName { get; set; }
        @AuraEnabled
        public Decimal quantity { get; set; }
        @AuraEnabled
        public String index { get; set; }
        @AuraEnabled
        public String id { get; set; }
        @AuraEnabled public Decimal length { get; set; }
        @AuraEnabled public Decimal width { get; set; }
        @AuraEnabled public Decimal height { get; set; }
        @AuraEnabled public Decimal CBM { get; set; }
        @AuraEnabled public Decimal Weight { get; set; }
        @AuraEnabled public Decimal units { get; set; }
        @AuraEnabled public Boolean stackable { get; set; }
        @AuraEnabled public Boolean palletized { get; set; }
        @AuraEnabled public String cargoDetails { get; set; }
    }
}